"""Locked out-of-sample holdout (LOCKED_NONCONSECUTIVE_HOLDOUT) invariant
tests. These are written and committed BEFORE any reserved-year strategy
performance is calculated (the PRE_OOS_LOCK commit) -- structural/causality
tests only, no result inspection. Run with:

    python3 -m pytest tests/test_oos_holdout.py -v
"""
from __future__ import annotations

import glob
import os
import sys

import numpy as np
import pandas as pd
import pytest

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO_ROOT)
OUT_DIR = os.path.join(REPO_ROOT, "outputs")

from scripts.stage2_engine import DEV_YEARS, RESERVED_YEARS  # noqa: E402
from scripts.oos_engine import (  # noqa: E402
    SELECTED_BLOCKS, SELECTED_CUTOFF_MINUTES, run_oos_replay,
    _diag_gaussian_loglik, _forward_filter_from_loglik,
)
from scripts.stage5_engine import in_allowed_blocks  # noqa: E402


def _rolling_ledger():
    p = os.path.join(OUT_DIR, "oos_ledger_rolling_python_hmm.csv")
    if not os.path.exists(p):
        pytest.skip("run scripts/run_oos_holdout.py first")
    df = pd.read_csv(p)
    for c in ["touched_at", "entry_time", "exit_time", "profit_lock_trigger_ts",
              "profit_lock_activation_ts", "hmm_last_bar_ts"]:
        df[c] = pd.to_datetime(df[c], utc=True, errors="coerce")
    return df


def _pine_ledger():
    p = os.path.join(OUT_DIR, "oos_ledger_frozen_pine_hmm.csv")
    if not os.path.exists(p):
        pytest.skip("run scripts/run_oos_holdout.py first")
    df = pd.read_csv(p)
    for c in ["touched_at", "entry_time", "exit_time"]:
        df[c] = pd.to_datetime(df[c], utc=True, errors="coerce")
    return df


def _executed(df):
    return df[df["skip_reason"].isna()].sort_values("entry_time").reset_index(drop=True)


# 1. No overlapping positions.
def test_no_overlapping_positions():
    d = _executed(_rolling_ledger())
    for i in range(1, len(d)):
        assert d.loc[i, "entry_time"] > d.loc[i - 1, "exit_time"], \
            f"overlap at row {i}: entry {d.loc[i,'entry_time']} <= prior exit {d.loc[i-1,'exit_time']}"


# 2. No same-minute exit and re-entry.
def test_no_same_minute_reentry():
    d = _executed(_rolling_ledger())
    for i in range(1, len(d)):
        assert d.loc[i, "entry_time"] != d.loc[i - 1, "exit_time"]


# 3. No retry after a consumed first touch (each level_id/side appears
# at most once anywhere in the ledger -- one physical touch, ever).
def test_no_retry_after_consumed_touch():
    df = _rolling_ledger()
    dup = df.groupby(["level_id", "side"]).size()
    assert (dup <= 1).all(), f"level_id/side appearing more than once: {dup[dup > 1]}"


# 4. No reserved-year result was calculated before PRE_OOS_LOCK.
# Structural proxy (runs both before and after the lock commit exists):
# the runner script must not import/execute anything at module import time
# that touches reserved-year ledgers, and no reserved-year ledger file may
# already exist in a commit tagged PRE_OOS_LOCK. This test asserts the
# convention: ledger files are gitignored from the PRE_OOS_LOCK commit by
# construction (checked manually at commit time, recorded in the commit
# message); here we simply assert the ledger, if present, is *newer* than
# the runner/engine source files it was produced from (i.e. it was
# generated by running the already-committed code, not hand-edited).
def test_ledger_not_older_than_engine_code():
    p = os.path.join(OUT_DIR, "oos_ledger_rolling_python_hmm.csv")
    if not os.path.exists(p):
        pytest.skip("run scripts/run_oos_holdout.py first")
    engine_mtime = os.path.getmtime(os.path.join(REPO_ROOT, "scripts", "oos_engine.py"))
    ledger_mtime = os.path.getmtime(p)
    assert ledger_mtime >= engine_mtime


# 5. HMM training excludes current and future sessions (trailing_sessions
# only ever returns sessions strictly before the target session).
def test_hmm_training_excludes_current_and_future_sessions():
    from scripts.stage4_regime_data import trailing_sessions
    all_sessions = [f"2020-01-{d:02d}" for d in range(1, 29)]
    for i, sess in enumerate(all_sessions):
        trailing = trailing_sessions(all_sessions, sess, max_sessions=120, min_sessions=1)
        if trailing is None:
            continue
        assert all(s < sess for s in trailing)
        assert sess not in trailing


# 6. Entry state uses only completed five-minute bars (state_before_rich /
# state_before_pine use entry_ts - 5min as the cutoff, never entry_ts itself).
def test_hmm_state_uses_only_completed_bars():
    from scripts.oos_engine import state_before_rich
    idx = pd.date_range("2020-01-02 18:00", periods=10, freq="5min", tz="UTC")
    df = pd.DataFrame({
        "state_label": ["LOW_VOL"] * 10, "max_prob": [0.9] * 10,
        "prob_LOW_VOL": [0.9] * 10, "prob_MID_VOL": [0.05] * 10, "prob_HIGH_VOL": [0.05] * 10,
    }, index=idx)
    cache_probs = {"2020-01-02": df}
    cache_meta = {"2020-01-02": {"n_train_sessions": 20, "earliest_train_session": "x",
                                  "latest_train_session": "y", "param_hash": "h"}}
    # entry exactly at bar idx[5]'s start: idx[5] has NOT completed yet
    # (needs +5min), so the last usable bar is idx[4] (started 5min earlier)
    entry_ts = idx[5]
    r = state_before_rich(cache_probs, cache_meta, "2020-01-02", entry_ts)
    assert r["hmm_last_bar_ts"] == idx[4]
    # entry 1 minute after bar idx[5] completes (idx[5] + 5min): idx[5]
    # itself is now the last usable bar
    entry_ts2 = idx[5] + pd.Timedelta(minutes=6)
    r2 = state_before_rich(cache_probs, cache_meta, "2020-01-02", entry_ts2)
    assert r2["hmm_last_bar_ts"] == idx[5]


# 7 & 8. Profit lock activates exactly one bar after its trigger bar, never
# on the trigger bar itself.
def test_profit_lock_activates_one_bar_after_trigger_never_on_trigger_bar():
    import scripts.stage3_engine as s3
    idx = pd.date_range("2020-01-02 14:30", periods=20, freq="1min", tz="UTC")
    entry = 100.0
    rows = []
    for i, ts in enumerate(idx):
        if i == 0:
            rows.append({"open": entry, "high": entry, "low": entry, "close": entry})
        elif i < 5:
            rows.append({"open": entry, "high": entry + 5, "low": entry - 0.1, "close": entry + 4})
        else:
            rows.append({"open": entry + 4, "high": entry + 4.2, "low": entry + 3.9, "close": entry + 4.1})
    bars = pd.DataFrame(rows, index=idx)
    touch_ts = idx[0]
    cutoff_ts = idx[-1]
    pnl, reason, exit_ts, audit = s3.simulate_exact_r_be(
        bars, touch_ts, cutoff_ts, entry, 1.0, tp_dist=100.0, sl_dist=5.0, trigger_r=0.75, lock_r=0.10)
    assert "trigger_bar_ts" in audit and "trigger_activated_ts" in audit
    trigger_bar_pos = list(idx).index(audit["trigger_bar_ts"])
    activated_pos = list(idx).index(audit["trigger_activated_ts"])
    assert activated_pos == trigger_bar_pos + 1, "activation must be exactly one bar after the trigger bar"


# 9. TP/SL are frozen at entry (never recomputed mid-trade) -- structural
# check: simulate_exact_r_be takes tp_dist/sl_dist as fixed scalar args and
# uses them unchanged for the entire loop (target/orig_stop are computed
# once before the bar loop).
def test_tp_sl_frozen_at_entry_by_construction():
    import inspect
    src = inspect.getsource(__import__("scripts.stage3_engine", fromlist=["simulate_exact_r_be"]).simulate_exact_r_be)
    # target and orig_stop must be assigned exactly once, before the loop
    assert src.count("target = entry") == 1
    assert src.count("orig_stop = entry") == 1


# 10. No entry occurs outside 05:00-11:00 (blocks E-I).
def test_no_entry_outside_selected_window():
    d = _executed(_rolling_ledger())
    assert (d["minutes_elapsed"] >= 660).all()
    assert (d["minutes_elapsed"] < 1020).all()
    assert d["window_allowed"].all()


# 11. No entry occurs in LOW_VOL.
def test_no_entry_in_low_vol():
    d = _executed(_rolling_ledger())
    assert (d["hmm_state"] != "LOW_VOL").all()
    assert d["hmm_allowed"].all()


# 12. MID_VOL and HIGH_VOL are allowed (both actually occur among executed trades).
def test_mid_and_high_vol_both_allowed():
    d = _executed(_rolling_ledger())
    states = set(d["hmm_state"].unique())
    assert states <= {"MID_VOL", "HIGH_VOL"}


# 13. No entry occurs at or after 15:59.
def test_no_entry_at_or_after_cutoff():
    d = _executed(_rolling_ledger())
    assert (d["minutes_elapsed"] < SELECTED_CUTOFF_MINUTES).all()


# 14. Every open trade is closed by 15:59 (exit_time <= session's 15:59 cutoff).
def test_every_trade_closed_by_cutoff():
    from scripts.stage5_engine import session_cutoff_ts
    d = _executed(_rolling_ledger())
    for _, row in d.iterrows():
        cutoff_ts = session_cutoff_ts(row["session_date"], SELECTED_CUTOFF_MINUTES)
        assert row["exit_time"] <= cutoff_ts


# 15. Physical first-touch ordering is unchanged (level_id/side appears at
# most once in the full master table -- verified directly against the
# upstream excursions parquet, independent of this stage's ledger).
def test_physical_touch_ordering_unchanged():
    exc = pd.read_parquet(os.path.join(OUT_DIR, "stage1_corrected_excursions.parquet"))
    assert exc["level_id"].is_unique


# 16. Re-running from the same locked commit and data hashes reproduces
# identical ledger hashes.
def test_reproducibility_hash_matches_report():
    p = os.path.join(OUT_DIR, "oos_final_report.json")
    if not os.path.exists(p):
        pytest.skip("run scripts/run_oos_holdout.py first")
    import json
    with open(p) as f:
        report = json.load(f)
    import hashlib
    d = _rolling_ledger()
    computed = hashlib.sha256(pd.util.hash_pandas_object(
        pd.read_csv(os.path.join(OUT_DIR, "oos_ledger_rolling_python_hmm.csv")), index=True).values.tobytes()).hexdigest()
    assert computed == report["hashes"]["ledger_rolling_hash"]


# ---------------------------------------------------------------------------
# Additional structural checks (not in the numbered 16, but directly
# relevant): reserved years never overlap dev years, and dev-year touches
# are never entered in the OOS replay.
def test_reserved_and_dev_years_disjoint():
    assert set(DEV_YEARS).isdisjoint(set(RESERVED_YEARS))


def test_no_dev_year_touch_ever_executed_in_oos_ledger():
    d = _rolling_ledger()
    executed = d[d["skip_reason"].isna()]
    assert set(executed["year"].unique()) <= set(RESERVED_YEARS)


def test_pine_ledger_restricted_to_2024_2025():
    d = _pine_ledger()
    executed = d[d["skip_reason"].isna()]
    assert set(executed["year"].unique()) <= {2024, 2025}


def test_pine_standalone_forward_filter_matches_reference_algorithm():
    """The standalone diag-Gaussian forward filter used for the frozen
    Pine application must be numerically identical to
    scripts.stage4_hmm.causal_forward_filter's algorithm."""
    rng = np.random.default_rng(0)
    n_obs, n_states = 12, 3
    log_probs = rng.normal(size=(n_obs, n_states))
    startprob = np.array([0.9, 0.08, 0.02])
    transmat = np.array([[0.8, 0.15, 0.05], [0.3, 0.5, 0.2], [0.1, 0.2, 0.7]])

    # reference: identical loop logic inlined here from stage4_hmm's algorithm
    probs = np.exp(log_probs - log_probs.max(axis=1, keepdims=True))
    alpha_ref = np.zeros((n_obs, n_states))
    a = startprob * probs[0]
    a = a / a.sum()
    alpha_ref[0] = a
    for t in range(1, n_obs):
        a = (alpha_ref[t - 1] @ transmat) * probs[t]
        a = a / a.sum()
        alpha_ref[t] = a

    alpha_test = _forward_filter_from_loglik(log_probs, startprob, transmat)
    assert np.allclose(alpha_ref, alpha_test)


if __name__ == "__main__":
    sys.exit(pytest.main([__file__, "-v"]))
